import React, { useState, useEffect } from 'react'
import { Card, CardHeader, CardContent, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { LoaderOne } from '@/components/ui/loader'
import { Button } from '@/components/ui/button'

const Generations = () => {
  const [generations, setGenerations] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchGenerations = async () => {
      try {
        const response = await fetch(`${import.meta.env.VITE_BACKEND_EXPRESS_API_URL}/ai/generations`, {
          credentials: 'include'
        });
        const data = await response.json();
        if (data.success) {
          setGenerations(data.data);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchGenerations();
  }, []);

  if (loading) return <div className="flex items-center justify-center min-h-[50vh]"><LoaderOne /></div>;

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight">AI Generations</h1>
        <p className="text-muted-foreground mt-2">View all your previous content generated by AI.</p>
      </div>
      
      <Tabs defaultValue="articles" className="w-full">
        <TabsList className="mb-6 bg-muted/50 p-1 rounded-lg">
          <TabsTrigger value="articles" className="rounded-md">Articles</TabsTrigger>
          <TabsTrigger value="titles" className="rounded-md">Blog Titles</TabsTrigger>
          <TabsTrigger value="images" className="rounded-md">Images</TabsTrigger>
          <TabsTrigger value="resumes" className="rounded-md">Resumes</TabsTrigger>
        </TabsList>
        
        <TabsContent value="articles" className="space-y-4">
          {(!generations?.articles || generations.articles.length === 0) ? (
             <div className="text-center py-12 bg-muted/20 rounded-lg border border-dashed border-muted-foreground/20">
               <p className="text-muted-foreground">No articles generated yet.</p>
             </div>
          ) : 
            generations.articles.map(item => (
              <Card key={item.id} className="overflow-hidden transition-all hover:shadow-md">
                <CardHeader className="bg-muted/30 border-b pb-4">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-lg font-semibold">{item.topic}</CardTitle>
                    <span className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">
                      {new Date(item.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <p className="line-clamp-4 text-sm text-muted-foreground leading-relaxed">
                    {item.result_text}
                  </p>
                </CardContent>
              </Card>
            ))
          }
        </TabsContent>

        <TabsContent value="titles" className="space-y-4">
          {(!generations?.titles || generations.titles.length === 0) ? (
             <div className="text-center py-12 bg-muted/20 rounded-lg border border-dashed border-muted-foreground/20">
               <p className="text-muted-foreground">No blog titles generated yet.</p>
             </div>
          ) : 
            generations.titles.map(item => (
              <Card key={item.id} className="overflow-hidden transition-all hover:shadow-md">
                <CardHeader className="bg-muted/30 border-b pb-4">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-lg font-semibold">{item.keyword}</CardTitle>
                    <span className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">
                      {new Date(item.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <p className="text-sm text-muted-foreground whitespace-pre-line leading-relaxed">
                    {item.result_text}
                  </p>
                </CardContent>
              </Card>
            ))
          }
        </TabsContent>

        <TabsContent value="images">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {(!generations?.images || generations.images.length === 0) ? (
               <div className="col-span-full text-center py-12 bg-muted/20 rounded-lg border border-dashed border-muted-foreground/20">
                 <p className="text-muted-foreground">No images generated yet.</p>
               </div>
            ) : 
              generations.images.map(item => (
                <Card key={item.id} className="overflow-hidden transition-all hover:shadow-md group">
                  <div className="aspect-square w-full overflow-hidden relative">
                    <img 
                      src={item.result_url} 
                      alt={item.prompt} 
                      className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105" 
                    />
                  </div>
                  <CardContent className="p-4 bg-card">
                    <p className="text-sm font-medium line-clamp-2 leading-tight" title={item.prompt}>{item.prompt}</p>
                    <div className="mt-3 flex justify-between items-center">
                      <span className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleDateString()}</span>
                      <span className="text-xs bg-secondary px-2 py-0.5 rounded-full capitalize">{item.style || "realistic"}</span>
                    </div>
                    <Button 
                      variant="ghost" 
                      size="sm" 
                      className="w-full mt-3 h-8 text-xs flex items-center justify-center gap-2 hover:bg-primary/5"
                      onClick={() => {
                        const link = document.createElement('a');
                        link.href = item.result_url;
                        link.download = `generation-${item.id}.png`;
                        document.body.appendChild(link);
                        link.click();
                        document.body.removeChild(link);
                      }}
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
                      Download
                    </Button>
                  </CardContent>
                </Card>
              ))
            }
          </div>
        </TabsContent>

        <TabsContent value="resumes" className="space-y-4">
          {(!generations?.resumes || generations.resumes.length === 0) ? (
             <div className="text-center py-12 bg-muted/20 rounded-lg border border-dashed border-muted-foreground/20">
               <p className="text-muted-foreground">No resumes reviewed yet.</p>
             </div>
          ) : 
            generations.resumes.map(item => (
              <Card key={item.id} className="overflow-hidden transition-all hover:shadow-md">
                <CardHeader className="bg-muted/30 border-b pb-4">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-lg font-semibold">Resume Review</CardTitle>
                    <span className="text-xs bg-primary/10 text-primary px-2 py-1 rounded-full">
                      {new Date(item.created_at).toLocaleDateString()}
                    </span>
                  </div>
                </CardHeader>
                <CardContent className="pt-4">
                  <p className="line-clamp-4 text-sm text-muted-foreground whitespace-pre-line leading-relaxed">
                    {item.analysis_result}
                  </p>
                </CardContent>
              </Card>
            ))
          }
        </TabsContent>

      </Tabs>
    </div>
  )
}

export default Generations
